name = "container"
version = "0.1.0"
defaultTargets = ["Container"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#master"

[leanOptions]
autoImplicit = false

[[lean_lib]]
name = "Container"
